### ISSUE TITLE
Decide on which UI framework to use

### ISSUE THREAD

**Issue by haimich** [bitionaire/el-bombillo#3]
There are a lot of CSS framework and helpers out there that make starting a new app much easier. Maybe we don't need a fully blown framework like Bootstrap, maybe we do - let's find out!

**Comment by haimich** [comment]
### CSS Preprocessor

Though the team behind CSS is making progress and implemting features only preprocessors have right now (like variables) I still think that it's valuable to have something like Less or Sass in your project because it makes writing clean code easier. I have only used Less so far but I'd go with Sass for this project because from reading a lot of blogs I think that most teams think that Sass is superior. As far as I know you need Ruby on your dev machine, I hope this doesn't come in our way.

**Comment by haimich** [comment]
### CSS Framework

Besides [Bootstrap](http://getbootstrap.com/) and [Foundation](https://github.com/angular-class/angular2-webpack-starter) (there's a version for "Sites" and one for "Apps", I think the latter suits us better) there is [PureCSS](http://getbootstrap.com/) we should consider when we go with a fully blown system. I'd really like to try out Foundation, but we should discuss first if we think that such a thing is the right thing to use.

At the other end of the spectrum there are smaller "libraries" like [Materialize](https://scotch.io/tutorials/make-material-design-websites-with-the-materialize-css-framework) that support building sites in a Material design style for example. Here are some more links regarding this whole topic: https://github.com/sotayamashita/awesome-css

What do you think?

**Comment by bitionaire** [comment]
We definitely have to use a CSS preprocessor, as it simplifies things alot. I really don't care whether it's Less or Sass because they're pretty similar. Sass has some extra features, that I've never intended to use so I've used only Less so far.

I also would like to discuss if we need a CSS framework at all, besides _normalize.js_ or something like that. A CSS framework makes it easier for a prototype but sometimes it's harder when you're starting with customizing your elements and layout. I have mixed feelings about e.g. Bootstrap so far.

If we choose to use a CSS framework though, I think we can quickly decide on the CSS preprocessor. We'll simply use the one that is used by the CSS framework. :)

**Comment by haimich** [comment]
I think developers are eager to use those frameworks because they get UI components created by real designers for free :-) If we can compensate that, I'm happy to try starting from scratch. Although I would rather not program my own grid system O_O

Maybe we could build our own (living) styleguide instead so it's easier for developers to program new ui components.

**Comment by bitionaire** [comment]
Agree!

It's easy to create your own grid system (especially with Less or Sass) though.

**Comment by johannes85** [comment]
There are many grid systems without a full blown design framework, or Frameworks without design, like: http://foundation.zurb.com/

**Comment by bitionaire** [comment]
Should we agree for now on a set of frameworks and start with a prototype? Then we'll maybe find out what fits us best and can switch to something different along the way.
- AngularJS on TypeScript (I already have an example for this locally)
- SASS
- Foundation
- Building it with Grunt (and let some watchers update the resources on change)

Another approach would be to define the UI in every detail (that we know of so far) and then search for a technology that fits best to our requirements. What do you feel more comfortable with?

**Comment by bitionaire** [comment]
So we setup the initial UI module `el-bombillo-ui` with the above mentioned technologies and see how things will unfold.
